#!/bin/bash
# ============================================================
# run-loop.sh — OpenCode Infinite Loop Runner
# Generated by opencode-infinite-loop skill
#
# Usage:
#   bash .opencode/run-loop.sh              # run up to MAX_ITERATIONS
#   bash .opencode/run-loop.sh 20           # override max iterations
#   bash .opencode/run-loop.sh 0            # run forever (no limit)
#
# The loop exits when:
#   1. The agent outputs <promise>COMPLETE</promise>
#   2. MAX_ITERATIONS is reached
#   3. You press Ctrl+C
# ============================================================

set -euo pipefail

# ---- Config ------------------------------------------------
MAX_ITERATIONS=${1:-50}          # Max loop iterations (0 = infinite)
AGENT="looper"                   # Primary agent name from opencode.json
PROMPT_FILE="PROMPT.md"          # Instruction file read each iteration
COMPLETION_TOKEN="<promise>COMPLETE</promise>"
SLEEP_BETWEEN=2                  # Seconds between iterations
LOG_FILE=".opencode/loop.log"    # Append-only log
# ------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Verify prerequisites
if ! command -v opencode &>/dev/null; then
  echo "❌ opencode not found in PATH. Install with: npm install -g opencode-ai"
  exit 1
fi

if [ ! -f "$PROJECT_ROOT/$PROMPT_FILE" ]; then
  echo "❌ $PROMPT_FILE not found in project root."
  echo "   Create it or re-run the opencode-infinite-loop skill setup."
  exit 1
fi

if [ ! -f "$PROJECT_ROOT/SPEC.md" ]; then
  echo "❌ SPEC.md not found in project root."
  echo "   The agent needs a spec to work from. Create SPEC.md first."
  exit 1
fi

# Initialize
mkdir -p "$PROJECT_ROOT/.opencode"
touch "$PROJECT_ROOT/progress.txt"
START_TIME=$(date +%s)

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "🚀 Starting OpenCode Infinite Loop"
log "   Agent:      $AGENT"
log "   Prompt:     $PROMPT_FILE"
log "   Max iters:  $( [ "$MAX_ITERATIONS" -eq 0 ] && echo "unlimited" || echo "$MAX_ITERATIONS" )"
log "   Log:        $LOG_FILE"
echo ""

# Main loop
iteration=0
while true; do
  iteration=$((iteration + 1))

  # Check iteration limit
  if [ "$MAX_ITERATIONS" -gt 0 ] && [ "$iteration" -gt "$MAX_ITERATIONS" ]; then
    log ""
    log "⚠️  Max iterations ($MAX_ITERATIONS) reached without completion."
    log "   Check progress.txt for what was completed and what blocked."
    log "   To continue: bash .opencode/run-loop.sh"
    exit 1
  fi

  ELAPSED=$(( $(date +%s) - START_TIME ))
  log "═══ Iteration $iteration / $( [ "$MAX_ITERATIONS" -eq 0 ] && echo "∞" || echo "$MAX_ITERATIONS" ) (${ELAPSED}s elapsed) ═══"

  # Run one iteration — attach to existing server if available, else standalone
  PROMPT_TEXT=$(cat "$PROJECT_ROOT/$PROMPT_FILE")

  OUTPUT=$(
    cd "$PROJECT_ROOT"
    opencode run \
      --agent "$AGENT" \
      --continue \
      --quiet \
      "$PROMPT_TEXT" 2>&1
  ) || {
    EXIT_CODE=$?
    log "⚠️  opencode run exited with code $EXIT_CODE — retrying next iteration"
    sleep "$SLEEP_BETWEEN"
    continue
  }

  # Print output
  echo "$OUTPUT"

  # Check for completion
  if echo "$OUTPUT" | grep -qF "$COMPLETION_TOKEN"; then
    log ""
    log "✅ COMPLETE after $iteration iteration(s)"
    TOTAL=$(( $(date +%s) - START_TIME ))
    log "   Total time: ${TOTAL}s"
    log "   Review: git log --oneline -20"
    log "   Review: cat progress.txt"
    exit 0
  fi

  # Brief pause before next iteration
  sleep "$SLEEP_BETWEEN"
done
