flowchart LR
  A[Rectangle]
  B(Rounded)
  C([Stadium])
  D[[Subroutine]]
  E[(Cylindrical)]
  F((Circle))
  G>Asymmetric]
  H{Rhombus}
  I{{Hexagon}}
  J[/Parallelogram/]
  K[\Trapezoid\]
  L[/Double Circle\]
  M[/Cylinder\]
