flowchart LR
  A --> B
  C --- D
  E -- text --- F
  G -->|text| H
  I -.- J
  K -.-|text| L
  M === N
  O ==>|text| P
  Q ~~~ R
  S --o T
  U --x V
  W <--> X
  Y --> Z --> AA --> AB
  AC & AD --> AE
